version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: ./apache/Dockerfile
    container_name: uploader
    ports:
    - "8000:80"
    - "5023:22"
    volumes:
    - "./project/:/var/www/html/uploader/project/"
    - "./storage/:/var/www/html/uploader/storage/"
    - "./uploads.ini:/etc/php/7.4/apache2/conf.d/uploads.ini"
    - "./uploads.ini:/etc/php/7.4/cli/conf.d/uploads.ini"
    - "./uploads.ini:/etc/php/7.4/fpm/conf.d/uploads.ini"
    - "./policy.xml:/etc/ImageMagick-6/policy.xml"
    links:
    - "mysql"
    depends_on:
    - phpmyadmin
    working_dir: /var/www/html/uploader/project
  mysql:
    image: mysql:5.7
    container_name: uploader_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "root"
      MYSQL_DATABASE: "uploader"
    ports:
    - "3317:3306"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    volumes:
    - /sessions
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      PMA_HOST: "mysql"
    ports:
    - "8003:80"
    links:
    - "mysql"
